version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: docker-lab-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
    - "27017:27017"
    volumes:
    - "./data:/data/db"

  mongo-express:
    image: mongo-express:latest
    container_name: docker-lab-mongo-express
    restart: always
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456

networks:
  default:
    external:
      name: docker-lab